### ISSUE TITLE
Issue with Ordered Lists

### ISSUE THREAD

**Issue by shanejones** [sanity-io/block-content-to-react#40] opened 2020-12-19 08:22 UTC
I'm using the default serializer with a few types for custom blocks

When using the list option in the editor, more specifically an ordered list, I can see that the content in the editor is numbered correctly.

When it comes to rendering this out on the frontend though, everything has the number 1 beside it.

The code shows that each list item is wrapped in an `<ol>` as you can see from this screenshot.
![Screenshot 2020-12-19 at 08 17 40](https://user-images.githubusercontent.com/325424/102684755-4830e180-41d3-11eb-9678-5c120e5897ce.jpg)

Is there anything I should be adding to add to the serializer to get these to group up into the same list?

**Comment by nzhenry** [comment] 2021-04-13 21:07
This issue is a duplicate of https://github.com/sanity-io/block-content-to-react/issues/23

This comment https://github.com/sanity-io/block-content-to-react/issues/23#issuecomment-668031729 should solve your problem.

**Comment by rexxars** [comment] 2023-01-31 01:15
Closing this, as the new `@portabletext/react` library is the successor to this module.
Please see https://github.com/portabletext/react-portabletext

**Closed by rexxars** 2023-01-31 01:15 UTC
