### ISSUE TITLE
List items being interpreted as lists?

### ISSUE THREAD

**Issue by OllieJT** [sanity-io/block-content-to-react#23] opened 2019-10-23 19:41 UTC
I am using block-content-to-react for some basic rich text. Somewhere in the pipeline it is turning what should be:
``` html
<ol>
   <li>Alpha<li>
   <li>Bravo<li>
   <li>Charlie<li>
</ol>
```
Into

``` html
<ol>
   <li>Alpha<li>
</ol>
<ol>
   <li>Bravo<li>
</ol>
<ol>
   <li>Charlie<li>
</ol>
```
Which is affecting the numberd list and intended spacing for the elements.
---

Here is what I have in sanity and what I expect:
![In Sanity](https://i.imgur.com/smwpiLq.png)

...but here in staging it breaks what should be a list into multiple lists:
![In Prod](https://i.imgur.com/6oCkiOE.png)

**Comment by luigimannoni** [comment] 2019-10-28 16:11
I am facing the exact same issue for the past 2 weeks, that was present on a 1.x.x release also updating to 2.0.7 doesn't solve the problem.

However got me thinking and found out that the list items are sent as single nodes rather than a node with multiple children.

One idea (which I haven't implemented due to time constraints) is to cycle on each node until the prop `listItems` doesn't exist anymore and then render the collected children on a custom component instead invoking the block serializer.

**Comment by runeb** [comment] 2020-08-03 13:45
@OllieJT @luigimannoni Are you by any chance sending each block item to the renderer separately? Like mapping over them and passing them in? That will produce this kind of output. If you instead pass in the whole array of block items it should render correctly.

**Comment by rexxars** [comment] 2022-02-01 21:33
If you are able to reproduce this issue in the [@portabletext/react](https://github.com/portabletext/react-portabletext) module, let us know!

Closing this as we are missing reproduction data.

**Closed by rexxars** 2022-02-01 21:33 UTC

**Comment by luigimannoni** [comment] 2022-02-01 22:11
Sorry @rexxars completely forgot about this issue.

Coincidentally I had picked up an old codebase in these weeks with this exact bug happening again after updating the block to content, latest sanity client and latest react.

I have solved by using `@portabletext/react` instead
